// Generated by diesel_ext

#![feature(proc_macro)]
#![allow(unused)]
#![allow(clippy::all)]

use chrono::prelude::*;
use chrono::DateTime;
use chrono::offset::Utc;
use diesel::sql_types::{Double, Jsonb};
use serde::{Serialize, Deserialize};


#[allow(non_camel_case_types)]
#[derive(DbEnum, Debug)]
pub enum Pending_transaction_nonce_type {
    Balance,
    Security,
    Dc
}

#[allow(non_camel_case_types)]
#[derive(DbEnum, Debug)]
pub enum Pending_transaction_status {
    Received,
    Pending,
    Failed
}

#[derive(Queryable, Debug)]
pub struct PendingTransaction {
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub hash: String,
    pub type_: crate::models::txn::Transaction_type,
    pub address: String,
    pub nonce: i64,
    pub nonce_type: Pending_transaction_nonce_type,
    pub status: Pending_transaction_status,
    pub failed_reason: Option<String>,
    pub data: Vec<u8>,
}
